random_seed: 0
batch_size: 512
n_epoch: 1000

train_root: 'dataGeneration/E1E2Data/train/'
val_root: 'dataGeneration/E1E2Data/val/'
formats: ['.csv']

optimizer: 'adam'
lr: 1e-5
weight_decay: 0
adam_eps: 1e-8
adam_amsgrad: True

input_key: 'A_abs'

CHECKPOINT_DIR: 'checkpoints/E1E2Data/'
LOSS_WEIGHT_DIR: 'configs/loss_weights/'

scheduler: 0.99