random_seed: 0
batch_size: 4
n_epoch: 100

train_root: 'dataGeneration/data/train/'
val_root: 'dataGeneration/data/val/'
formats: ['.csv']

optimizer: 'adam'
lr: 1e-3
weight_decay: 0
adam_eps: 1e-8
adam_amsgrad: False

CHECKPOINT_DIR: 'checkpoints/Basic/'